# Numpy

on anaconda prompt in the right environment 
run
`conda install numpy` or `pip install numpy`

In [1]:
import numpy as np

In [2]:
lst = [1,2,3]
lst

[1, 2, 3]

In [3]:
type(lst)

list

In [4]:
np.array(lst)

array([1, 2, 3])

In [5]:
mat = [ [1,2,3], [4,5,6], [7,8,9]]

In [6]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [10]:
np.arange(5, 30, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

## zeros and ones

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.zeros( (5,5 ) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
np.linspace(1, 9, 7)

array([1.        , 2.33333333, 3.66666667, 5.        , 6.33333333,
       7.66666667, 9.        ])

## eye

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random numbers

In [18]:
np.random.rand(2)

array([0.83473194, 0.52284736])

In [19]:
np.random.rand(5,5)

array([[0.16920549, 0.73207886, 0.28306212, 0.47203474, 0.5824774 ],
       [0.1265062 , 0.04620231, 0.06462594, 0.35585651, 0.10169843],
       [0.14099019, 0.41505322, 0.20230634, 0.76221955, 0.03494687],
       [0.32155821, 0.14310984, 0.48808197, 0.20829557, 0.10470441],
       [0.56271954, 0.84430572, 0.50812934, 0.94777794, 0.50201769]])

In [20]:
#uniform normal
np.random.randn(5,5)

array([[-1.08033952, -0.28559799, -0.46653164, -0.28563255, -0.04329063],
       [ 0.06184986,  1.78090228, -1.51028493, -0.10551051,  2.14431304],
       [ 0.73039918,  0.6547262 , -2.19953193,  0.34538648, -1.07281717],
       [ 1.09701834,  0.61180987, -0.22916678,  0.58952927, -0.60502602],
       [-0.27212186, -0.10705882,  0.86601339,  0.69281285,  1.44731769]])

In [21]:
np.random.randint(1,100)

4

In [22]:
np.random.randint(3,25, 100)

array([ 3, 12, 18, 16, 17, 11, 20, 17,  3, 20,  8, 16, 20,  3, 15, 24, 23,
        6, 17,  3,  7, 13,  9, 14, 24, 17, 14, 17, 20,  6, 17, 15, 24, 24,
       12, 21, 20, 13, 22,  6, 14, 24, 15,  5,  9, 18, 14, 11, 19,  3, 12,
       22,  9,  3, 22,  3,  6,  5,  3, 16, 24,  8, 18, 14, 11,  8,  6, 23,
        4,  8, 13,  4, 13, 15, 11, 20, 13, 19,  5, 23, 18,  5, 18, 18, 13,
       23,  8, 17, 10,  9, 22, 10, 10, 21,  3, 19, 11,  4, 19,  5])

# Array attributes and methods

In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([33, 31, 45, 39, 26, 33, 47,  9, 17, 12])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
x = arr.reshape(5,5)

In [29]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
## min, max, etc

In [31]:
ranarr

array([33, 31, 45, 39, 26, 33, 47,  9, 17, 12])

In [32]:
ranarr.max()

47

In [33]:
ranarr.min()

9

In [34]:
ranarr.argmax()

6

In [35]:
ranarr.argmin()

7

## shape

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(5,5).shape

(5, 5)

In [38]:
arr.shape

(25,)

In [39]:
type((25,))

tuple

In [40]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

# Indexing and Selection

In [41]:
arr = np.arange(11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting

In [45]:
lst = [1,2,3]

In [46]:
lst[0:2] = 99

TypeError: can only assign an iterable

In [47]:
lst[0:2] = [98,99]

In [48]:
lst

[98, 99, 3]

In [49]:
arr[0:5] = 101

In [50]:
arr

array([101, 101, 101, 101, 101,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(11)

In [52]:
slice_arr = arr[0:6]

In [53]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [54]:
slice_arr[:] = 999

In [55]:
slice_arr

array([999, 999, 999, 999, 999, 999])

In [56]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

In [57]:
arr_copy = arr.copy()

In [58]:
arr_copy[0:4] = 33

In [59]:
arr_copy

array([ 33,  33,  33,  33, 999, 999,   6,   7,   8,   9,  10])

In [60]:
arr

array([999, 999, 999, 999, 999, 999,   6,   7,   8,   9,  10])

## Indexing 2D

In [61]:
arr_2d = np.arange(5,50,5).reshape(3,3)

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[1]

array([20, 25, 30])

In [64]:
arr_2d[1][0]

20

In [65]:
arr_2d[1,0]

20

In [66]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[2,:]

array([35, 40, 45])

## Fancy indexing

In [69]:
arr2d = np.zeros((10,10))

In [70]:
arr_length = arr2d.shape[1]

In [71]:
 arr2d.shape[1]

10

In [72]:
for i in range(arr_length):
    arr2d[i] = i

In [73]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [74]:
arr2d[ [2,4,6,8] ]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [75]:
arr2d[ [6,2,9,4]  ]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [76]:
arr = np.arange(1,11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr = arr > 4

In [80]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr[ arr > 2 ]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
x = 6
arr[arr < x]

array([1, 2, 3, 4, 5])

## operations

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr / arr

C:\Anaconda\2\envs\cobra\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [90]:
1 / arr

C:\Anaconda\2\envs\cobra\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [91]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [93]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [94]:
np.log(arr)

C:\Anaconda\2\envs\cobra\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])